version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: dependencies.sh
      timeout: 6000
      runas: ec2-user
  AfterInstall:
    - location: migrate.sh
      timeout: 6000
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 6000
      runas: ec2-user