version: 0.0
os: linux
files:
  - source: /
    destination: /root
hooks:
  BeforeInstall:
    - location: /root/dependencies.sh
      runas: root
  AfterInstall:
    - location: /root/migrate.sh
      runas: root
  ApplicationStart:
    - location: /root/start.sh
      runas: root
