# Generated by Django 3.1.7 on 2021-04-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('faculty', models.EmailField(max_length=100)),
                ('students', models.ManyToManyField(to='user_management.User')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('moduleId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course_management.course')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('evaluationComponentId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('noOfQuestions', models.IntegerField()),
                ('dateTime', models.CharField(max_length=200)),
                ('type', models.CharField(default='QUIZ', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluationComponents', to='course_management.course')),
            ],
        ),
    ]
