# Generated by Django 3.1.7 on 2021-02-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_auto_20210219_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('moduleId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
            ],
        ),
    ]
