# Generated by Django 3.1.7 on 2021-02-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0006_auto_20210220_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('evaluationComponentId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
                ('noOfQuestions', models.IntegerField()),
                ('dateTime', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluationComponents', to='course_management.course')),
            ],
        ),
    ]
