# Generated by Django 3.2.4 on 2021-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hasRead',
            field=models.BooleanField(default=False),
        ),
    ]
